### ISSUE TITLE
[Bug] `input` gets out of bounds

### ISSUE THREAD

**Issue by LEv145** [canisminor1990/sd-webui-kitchen-theme#80]
### 💻 系统环境 | Operating System

Other Linux

### 🌐 浏览器 | Browser

Firefox

### 🐛 问题描述 | Bug Description

![image](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/40071054/57a06dd9-eace-4b29-bd4f-752c7d9bf003)
![image](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/40071054/92dfbf35-709e-4db0-8ec3-62054e6afdfc)

### 📝 补充信息 | Additional Information

My solution:
```css
#quicksettings input[type="number"] {
    max-width: 85px;
}
```
